import { NextResponse } from "next/server";

const now = Date.now();

const notifications = [
  {
    id: "notif_001",
    recipient_id: "student_001",
    type: "info",
    priority: "urgent",
    title: "Google Placement Drive Invitation",
    message: "You have been invited to the Google placement drive. Submit your application by tomorrow.",
    notification_type: "Placement",
    status: "delivered",
    is_read: false,
    created_at: new Date(now - 10 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_002",
    recipient_id: "student_001",
    type: "warning",
    priority: "high",
    title: "Semester Result Released",
    message: "Your semester result has been released. Check your dashboard for full details.",
    notification_type: "Result",
    status: "delivered",
    is_read: false,
    created_at: new Date(now - 35 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_003",
    recipient_id: "student_001",
    type: "info",
    priority: "normal",
    title: "Campus Hackathon Tomorrow",
    message: "Join the campus hackathon tomorrow at 10 AM in the main auditorium.",
    notification_type: "Event",
    status: "scheduled",
    is_read: false,
    created_at: new Date(now - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_004",
    recipient_id: "student_002",
    type: "success",
    priority: "low",
    title: "Alumni Meetup Reminder",
    message: "The alumni meetup is happening this weekend. RSVP to secure your seat.",
    notification_type: "Event",
    status: "sent",
    is_read: true,
    created_at: new Date(now - 18 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_005",
    recipient_id: "student_002",
    type: "warning",
    priority: "high",
    title: "Interview Slot Confirmed",
    message: "Your interview slot for the placement drive has been confirmed.",
    notification_type: "Placement",
    status: "delivered",
    is_read: false,
    created_at: new Date(now - 80 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_006",
    recipient_id: "student_003",
    type: "info",
    priority: "normal",
    title: "Library Fine Reminder",
    message: "Your library books are due in 2 days. Return or renew to avoid fines.",
    notification_type: "Event",
    status: "pending",
    is_read: true,
    created_at: new Date(now - 36 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_007",
    recipient_id: "student_001",
    type: "warning",
    priority: "urgent",
    title: "Exam Deadline Extended",
    message: "The final exam deadline has been extended by 2 days.",
    notification_type: "Result",
    status: "delivered",
    is_read: false,
    created_at: new Date(now - 50 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_008",
    recipient_id: "student_004",
    type: "success",
    priority: "low",
    title: "Sports Event Invitation",
    message: "Get ready for the annual sports day this Saturday.",
    notification_type: "Event",
    status: "scheduled",
    is_read: false,
    created_at: new Date(now - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_009",
    recipient_id: "student_001",
    type: "info",
    priority: "high",
    title: "Placement Offer Reminder",
    message: "One of your placement offers expires in 24 hours. Review your options.",
    notification_type: "Placement",
    status: "delivered",
    is_read: false,
    created_at: new Date(now - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_010",
    recipient_id: "student_005",
    type: "info",
    priority: "normal",
    title: "Workshop Registration Closed",
    message: "Registration for the machine learning workshop has now closed.",
    notification_type: "Event",
    status: "closed",
    is_read: true,
    created_at: new Date(now - 40 * 60 * 60 * 1000).toISOString(),
  },
];

export async function GET() {
  return NextResponse.json(notifications);
}
